name: 'Typing - Readme SVG Text'
author: 'Tonal Mathew'
description: 'Text to svg in readme'

inputs:
  INPUT_TEXT:
    description: 'Text to be displayed as svg'
    required: true
    type: string
    multiline: true
  COLOR: 
    description: 'Text color'
    default: '#36BCF7'
    required: false
  COMMITTER_NAME:
    description: 'Name of the committer'
    default: 'github-actions[bot]'
    required: false
  COMMITTER_EMAIL: 
    description: 'Email of the committer'
    default: '41898282+github-actions[bot]@users.noreply.github.com'
    required: false

branding:
  color: blue
  icon: activity

runs: 
  using: 'node16'
  main: 'dist/index.js'